## Numpy

In [ ]:
import numpy as np
import time

### creating array from list

In [ ]:
array = np.array([12,3,4,5,66,7,7,978])
print(array)

In [ ]:
twodarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twodarray)

In [ ]:
threeDarray = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(threeDarray)

### list vs array



In [ ]:
plst= [1,2,3]
print(plst*2)

parray= np.array([1,2,3,])  # element wise multiplication
print(parray*2)

In [ ]:
start= time.time()
plist = [i*2 for i in range(1000000)]
print("Time taken for list: ", time.time()-start)

start= time.time()
parray = np.array([i*2 for i in range(10000000)])
print("Time taken for array: ", time.time()-start)

start= time.time()
parraya = np.arange(10000000)*2
print("Time taken for array from arrange method : ", time.time()-start)

### creating array from scratch


In [ ]:
zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((5,3))
print("araay of ones\n",ones)

full=np.full((2,3),7)
print(full)

random= np.random.random((2,3))
print("random array: \n", random*1000000)

sequence= np.arange(0,21,2)   # start stop step , range in python is non inclusive outer boundary 
print("sequential array \n",sequence)



### vector , Matrix & tensor


In [ ]:
vectors = np.array([1,3,5,7])
print("vectors: \n",vectors)

matrix = np.matrix([[2,4,6],[7,5,9]])
print("matrix: \n",matrix)

tensor =np.array([[[1,2],[3,5]],[[2,6],[3,9]]])
print("tensor: \n",tensor)






### Array properties 

In [ ]:
arry=np.array([[1,2,3],[1,4,5],[3,4,9]])
print("Shape: ",arry.shape)
print("Dimention: ", arry.ndim)
print("Size: ", arry.size)
print("Data type: ",arry.dtype)




### Array Reshaping

In [29]:
arrayy= np.arange(10)
print("Original array: ",arrayy)

reshaped= arrayy.reshape((2,5))
print("reshaped array: \n", reshaped)

flattend= reshaped.flatten()
print("flattend array:\n",flattend)

# ravel (return view insted of copy )
raveled = reshaped.ravel()
print("raveled array:\n",raveled)

# Transpose
transposed = reshaped.T
print("transpose matrix:\n",transposed)
  


Original array:  [0 1 2 3 4 5 6 7 8 9]
reshaped array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
flattend array:
 [0 1 2 3 4 5 6 7 8 9]
raveled array:
 [0 1 2 3 4 5 6 7 8 9]
transpose matrix:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
