## Numpy Array Oppertaion 

In [7]:
import numpy as np


In [8]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print("basic indexing: \n",arr[2:7])
print("with step:\n ",arr[1:7:3])
print("negetive indexing: \n",arr[-6])

basic indexing: 
 [3 4 5 6 7]
with step:
  [2 5]
negetive indexing: 
 5


In [9]:
twoDarray= np.array([[1,3,4,6],
                     [1,5,8,3],
                     [0,9,8,7]])
print("spesific element: ",twoDarray[1,3])
print("entire row: ",twoDarray[1,:])
print("entire column: ",twoDarray[:,3])
x= twoDarray[:,3]
print(x.transpose)


spesific element:  3
entire row:  [1 5 8 3]
entire column:  [6 3 7]
<built-in method transpose of numpy.ndarray object at 0x0000023AFF0EFB70>


## Sorting 

In [10]:
unsorted = np.array([1,2,3,5,6,12,2,4,8,9,1,90,70,2,3,5])
print("sorted array:",np.sort(unsorted))

twoDunsortedarray= np.array([ [1,2,4,5]
                             ,[9,7,5,4]
                             ,[5,6,7,9]
                             ,[1,9,0,2]])
print("sorted 2D array coulmn: \n ",np.sort(twoDunsortedarray,axis=0))
print("sorted 2D array row: \n ",np.sort(twoDunsortedarray,axis=1))


sorted array: [ 1  1  2  2  2  3  3  4  5  5  6  8  9 12 70 90]
sorted 2D array coulmn: 
  [[1 2 0 2]
 [1 6 4 4]
 [5 7 5 5]
 [9 9 7 9]]
sorted 2D array row: 
  [[1 2 4 5]
 [4 5 7 9]
 [5 6 7 9]
 [0 1 2 9]]


## Filtering

In [11]:
num=np.array([1,5,8,6,3,7,2,4,10,15,20])
evenNumbers = num[num%2==0]
print("even numbers: \n",np.sort(evenNumbers))

even numbers: 
 [ 2  4  6  8 10 20]


## Filter with mask 

In [12]:
anArray = np.array([5,9,6,8,2,4,6,1,2,3,4,5,6,7,8,9,10,15,16,20,41,29,31])
mask = anArray>10
print("No.greater than 10: ",np.sort(anArray[mask]) )

No.greater than 10:  [15 16 20 29 31 41]


## Fancy indexing v/s np.where()

In [13]:
anArrayfindex = np.array([5,9,6,8,9,4,6,8,3,78,3,4,5,6,7,8,9,10,15,16,20,41,29,31])
indices=[1,5,9,0,6,4]
print(anArrayfindex[indices])

whereResult= np.where(anArrayfindex>10)
print("NP where",np.sort(anArrayfindex[whereResult]))
print("NP where",np.shape(anArrayfindex[whereResult]))
print(whereResult)

[ 9  4 78  5  6  9]
NP where [15 16 20 29 31 41 78]
NP where (7,)
(array([ 9, 18, 19, 20, 21, 22, 23]),)


#### np. whre is used too create array only but with some conditions.

In [14]:
array=np.array([5,8,9,6,2,31,4,5,4,9,4,32,1,5,61,5,65,12])
conditionArray = np.where(array>20,array*2,array)
print("condition Array: ",conditionArray)

condition Array:  [  5   8   9   6   2  62   4   5   4   9   4  64   1   5 122   5 130  12]


## Adding and removing data 

In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,0])
print(arr1+arr2)  # this will add the te elements 
concatinate = np.concatenate((arr1,arr2))
print(concatinate)

[ 7  9 11 13  5]
[1 2 3 4 5 6 7 8 9 0]


## array compatibility

In [16]:
a= np.array([1,2,3])
b= np.array([4,5,5,6])
c= np.array([7,8,1,6,9])
print("compatobility ahapes: ",a.shape==b.shape)


compatobility ahapes:  False


In [17]:
original = np.array([[1,3],[3,4]])
new_row= np.array([[5,6]]) 
with_new_row = np.vstack((original,new_row))
print(with_new_row)
new_col= np.array([[7,9],[9,2]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 3]
 [3 4]
 [5 6]]
[[1 3 7 9]
 [3 4 9 2]]


In [18]:
ar= np.array([1,2,3,5,7,8])
deleted = np.delete(ar,3)
print("the array after delition: ",deleted)

the array after delition:  [1 2 3 7 8]
